# Site wide configuration

title:            Houstairs 
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: J.Pérez-Sorrosal
  avatar: bio-photo-yo.jpg
  bio: "Keep learning."
  email: 
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-50762298-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #jperezsorrosal
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #jperezsorrosal
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #jperezsl

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
